//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsHystory
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Script { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> Date { get; set; }

        public OperationsHystory() { }

        public OperationsHystory(Operation operation, string field1, string field2,
            string result, DateTime date)
        {
            ID = operation.ID;
            Name = operation.Name;
            Script = operation.Script;
            Field1 = field1;
            Field2 = field2;
            Result = result;
            Date = date;
        }
    }
}
